version: 2.1
jobs:
  deploy:
    docker:
      - image: alpine
    steps:
      - run:
          name: Despliegue
          command: |
            apk update
            apk add openssh
            ssh $SRV_USR@$SRV_IP
            echo $SRV_PASS
            docker pull yovafree/test-front:latest
            docker run -d -p 80:80 --name test-front yovafree/test-front:latest
            exit
            echo 'Despliegue exitoso'

