version: 2.1
jobs:
  build:
    docker:
      - image: docker:18-git
    steps:
      - run:
          name: Crear imagen de docker
          command: |
            echo 'Se inicia la compilacion'
            ls -l
            docker build -t yovafree/test-front:latest .
            echo 'Se inicia la compilacion'