version: 2.1
jobs:
  build:
    docker:
      - image: docker:18-git
    working_directory: ~/test-front
    steps:
      - checkout
      - run:
          name: Crear imagen de docker
          command: |
            echo 'Se inicia la compilacion'
            ls
            cd test-front && docker build -t yovafree/test-front:latest .
            echo 'Se inicia la compilacion'