version: 2.1
jobs:
  build:
    docker:
      - image: docker:18-git
    working_directory: ~/test-front
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Crear imagen de docker
          command: |
            echo 'Se inicia la compilacion'
            ls
            docker login -u $docker_usr -p $docker_pass
            docker build -t yovafree/test-front:latest .
            docker push yovafree/test-front:latest
            echo 'Se inicia la compilacion'
  deploy:
    docker:
      - image: alpine
    steps:
      - run:
          name: Despliegue
          command: |
            apk update
            apk add openssh
            apk add sshpass
            sshpass -p $SRV_PASS ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $SRV_USR@$SRV_IP 'docker pull yovafree/test-front:latest; docker run -d -p 80:80 --name test-front yovafree/test-front:latest; exit'
            echo 'Despliegue exitoso'

workflows:
    flujo:
      jobs:
        - build:
            type: approval
        - deploy