apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-test-deployment
  labels:
    app: frontend-test-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-test-app
  template:
    metadata:
      labels:
        app: frontend-test-app
    spec:
      containers:
      - name: frontend-test
        image: pensotec.com:5005/egdeleon/test-front:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always
      imagePullSecrets:
       - name: gitlab-docker-registry
